version: '3'
services:
 db:
  image: 'mysql:8'
  networks:
   - customer-mysql
  ports:
   - "3306:3306"
  environment:
   - MYSQL_ROOT_PASSWORD=Welcome123
   - MYSQL_DATABASE=customer
  healthcheck:
   test: ["CMD","mysqladmin","ping","-h","localhost"]
   timeout: 20s
   retries: 10
  restart: always
 backendserver:
  image: 'hassanhochlef/projetachat:latest'
  ports:
   - "8089"
  networks:
   - customer-mysql
  links:
   - "db"
  depends_on:
   - "db"
 frontend:
  image: 'hassanhochlef/projetachat:latest'
  links:
   - "backendserver"
  depends_on:
   - "backendserver"
  ports:
   - "80:80"
networks:
 customer-mysql:
