version: '3'
services:
 db:
  image: 'mysql:8'
  networks:
   - customer-mysql
  environment:
      MYSQL_ROOT_PASSWORD: Welcome123
      MYSQL_DATABASE: customer
  ports:
   - "3306:3306"
  volumes:
   - db:/var/lib/mysql
  healthcheck:
   test: ["CMD","mysqladmin","ping","-h","localhost"]
   timeout: 20s
   retries: 10
  restart: always
 backendserver:
  image: 'hassanhochlef/projetachat:latest'
  ports:
   - "8089"
  networks:
   - customer-mysql
  volumes:
      - .m2:/root/.m2
  stdin_open: true
  tty: true
  links:
   - "db"
  depends_on:
   - "db"
 frontend:
  image: 'hassanhochlef/projetachat:latest'
  links:
   - "backendserver"
  depends_on:
   - "backendserver"
  ports:
   - "80:80"
networks:
 customer-mysql:
